### ISSUE TITLE
macOS Unable to build

### ISSUE THREAD

**Issue by InochiPM** [adlez27/akorin#21]
When i open it in VS for mac i can get it to build but it throws an error when it tries to launch, as well as 60+ warnings about the code. 
I also cannot use .NET 5.0 because its unsupported, so when i try to up it to 6.0 it seems to work but i'm guessing thats where the warnings come from. 

<img width="1078" alt="Screenshot 2022-08-19 at 2 16 40 PM" src="https://user-images.githubusercontent.com/13459080/185682040-9b70739d-bf25-4aba-b061-ad57a2f76410.png">

**Comment by InochiPM** [comment]
I also got it to build with the console command but the program will not open at all. i followed the instructions but "remove signature" isn't an item in the plst file

`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libbass, 0x0001): tried: 'libbass' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibbass' (no such file), '/usr/lib/libbass' (no such file, not in dyld cache), 'libbass' (no such file), '/usr/local/lib/libbass' (no such file), '/usr/lib/libbass' (no such file, not in dyld cache)
   at ManagedBass.Bass.Init(Int32 Device, Int32 Frequency, DeviceInitFlags Flags, IntPtr Win, IntPtr ClsID)
   at Akorin.Models.Settings..ctor(Boolean startup) in /Users/inochipm/Documents/GitHub/akorin/Akorin/Models/Settings.cs:line 229
   at Akorin.App.Initialize() in /Users/inochipm/Documents/GitHub/akorin/Akorin/App.axaml.cs:line 15
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 310
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Akorin.Program.Main(String[] args) in /Users/inochipm/Documents/GitHub/akorin/Akorin/Program.cs:line 13
zsh: abort      

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

`

**Comment by adlez27** [comment]
Akorin is no longer in development. Any interested users should use RecStar instead.

https://github.com/sdercolin/recstar/
